site_name: PyGo
site_author: 'Paul Schick'
site_url: 'https://pygo-alpha.paulschick.dev'
copyright: '&copy; 2021 Paul Schick'
docs_dir: 'docs'
nav:
  - Home: index.md
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  features:
    - tabs
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: assets/icon.png
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.inlinehilite
